SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5D4A8E6F2C974413}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{61F978CD472C7B25}" : "{E44092EA8D23FA22}Configs/EntityCatalog/Shared/SimpleGPS_ArsenalEntry.conf" {
    }
   }
  }
 }
}
