SCR_EntityCatalogInventoryItem {
 m_sEntityPrefab "{BBBFDE74332B7D1D}Prefabs/Items/Equipment/GPS/NCM_GPS_Item.et"
 m_aEntityDataList {
  SCR_ArsenalItem "{0B42123F5AB955C9}" {
   m_eItemType EQUIPMENT
   m_iSupplyCost 0
  }
 }
}
