SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5D4A87E86D216247}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{2B905816BA4449D4}" : "{E44092EA8D23FA22}Configs/EntityCatalog/Shared/SimpleGPS_ArsenalEntry.conf" {
    }
   }
  }
 }
}
